name: the_tipping_jar
description: "The Tipping Jar â€” fan tipping platform for creators"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^13.2.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  file_picker: ^8.0.0+1
  flutter_spinkit: ^5.2.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
